### ISSUE TITLE
Error at your verification

### ISSUE THREAD

**Issue by kazotka** [fidilen/discord-modmail#1]
There's a small error in your code! In the file `discord-modmail-master\functions` you need to change line 7 & 11 in the file `discord-modmail-master\functions\close.js`, because when you write `interaction.reply` it's already been sent, so you need to change it to this: `interaction.followUp`. The same goes for the `discord-modmail-master\functions\reply.js` file at line 9 & 12, where you do the same thing.

**Comment by fidilen** [comment]
Thanks for reporting! I have applied the necessary changes. 😊
